import { User } from '../models/user';

export const MockUsers: User[] = [
  {
    id: 1,
    name: 'Beatriz',
    lastname: 'Maravilla',
    email: 'BeaMara@gmail.com',
    username: 'BeaMara',
    password: '123456',
  },
  {
    id: 2,
    name: 'Juan',
    lastname: 'Pérez',
    email: 'juan.perez@gmail.com',
    username: 'juanp',
    password: 'password1',
  },
  {
    id: 3,
    name: 'María',
    lastname: 'García',
    email: 'maria.garcia@gmail.com',
    username: 'mariag',
    password: 'password2',
  },
  {
    id: 4,
    name: 'Carlos',
    lastname: 'Sánchez',
    email: 'carlos.sanchez@gmail.com',
    username: 'carloss',
    password: 'password3',
  },
  {
    id: 5,
    name: 'Ana',
    lastname: 'López',
    email: 'ana.lopez@gmail.com',
    username: 'anal',
    password: 'password4',
  },
  {
    id: 6,
    name: 'Pedro',
    lastname: 'Martínez',
    email: 'pedro.martinez@gmail.com',
    username: 'pedrom',
    password: 'password5',
  },
  {
    id: 7,
    name: 'Sofía',
    lastname: 'Fernández',
    email: 'sofia.fernandez@gmail.com',
    username: 'sofiaf',
    password: 'password6',
  },
  {
    id: 8,
    name: 'David',
    lastname: 'Rodríguez',
    email: 'david.rodriguez@gmail.com',
    username: 'davidr',
    password: 'password7',
  },
  {
    id: 9,
    name: 'Elena',
    lastname: 'Díaz',
    email: 'elena.diaz@gmail.com',
    username: 'elenad',
    password: 'password8',
  },
  {
    id: 10,
    name: 'Ricardo',
    lastname: 'Gómez',
    email: 'ricardo.gomez@gmail.com',
    username: 'ricardog',
    password: 'password9',
  },
];
